# Generated by Django 3.1.4 on 2020-12-11 12:23

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('polls_cms_integration', '0004_multilanguagesexample_multilanguagesexampletranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multilanguagesexampletranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='multilanguagesexampletranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='my_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='my_placeholder', to='cms.placeholder'),
        ),
        migrations.DeleteModel(
            name='MultiLanguagesExample',
        ),
        migrations.DeleteModel(
            name='MultiLanguagesExampleTranslation',
        ),
    ]
