# Generated by Django 3.1.4 on 2020-12-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0005_auto_20201211_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
